contact_links:
  - name: If you have any questions, please join the QQ group. / 有疑问请加QQ群
    url: https://github.com/go-musicfox/go-musicfox/issues/25
    about: Raise your questions and we will try our best to resolve them. / 提出你的疑问，我们尽可能地解决
