contact_links:
  - name: If you have any questions, please join the Telegram group. / 有疑问请加Telegram群
    url: https://t.me/+jp9qIwWw16k5MjU1
    about: Raise your questions and we will try our best to resolve them. / 提出你的疑问，我们尽可能地解决
